# Jekyll site configuration file

title: dblog # The title of your site, shown in the browser tab and used in meta tags for SEO.

# This description appears in the <meta> tag for SEO purposes and helps with search engine rankings.
description: >-
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

url: "https://sionta-dblog.vercel.app" # The full base URL of your site (e.g., https://example.com). Required for generating absolute links.
baseurl: "" # If your site is hosted in a subfolder (e.g., /blog), define the subpath here. Otherwise, leave it empty.

#brand: dblog
#image: "/assets/img/logos/logo.svg"

#copyright: >-
#   &copy; :year: :title:. All Rights Reserved. Designed with love by
#   <a href="https://github.com/sionta">Andre Attamimi</a>

# For SEO and default post author
author: &DEFAULT_AUTHOR
  name: "Andre Attamimi"
  twitter: "r007mmxv"
  email: "rumatua0@gmail.com"
  url: "https://github.com/sionta"
  picture: "/assets/images/logo.svg"

# Social media links and RSS feed subscription button. Icons are from Tabler Icons (https://tabler.io/icons)
social_media:
  - { name: "Subcribe", icon: "rss", url: "feed.xml" }
  - { name: "Email", icon: "mail", url: "mailto:info@andreattamimi.com" }
  - { name: "GitHub", url: "https://github.com/sionta" }
  - { name: "Mastodon", url: "https://mastodon.social/@sionta" }
  - { name: "Twitter", icon: "brand-x", url: "https://twitter.com/r007mmxv" }

# Post comments
# NB: giscus and utterances requirer on public repo.
comments:
  provider: "" # (e.g. disqus), The provider settings below:
  disqus: # What is `shortname` see https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: ""
  giscus: # For more settings see https://giscus.app/
    repo: ""
    repo_id: ""
    category: ""
    category_id: ""
  utterances: # For more setting see to https://utteranc.es/
    repo: ""
    label: ""
    issue_term: ""

# PLEASE DONT MODIFY AFTER THIS LINE ********************************

# Table of Contents (TOC) settings
toc:
  min_level: 1 # Minimum heading level to include in the table of contents (e.g., H1).
  max_level: 2 # Maximum heading level to include in the table of contents (e.g., H2).
  ordered_list: false # Use an unordered list (false) or ordered list (true) for the TOC.
  no_toc_section_class: # Section classes that will exclude TOC from being generated.
    - "no_toc"
    - "no-toc"
  list_id: "toc-list" # ID for the generated TOC list element.
  list_class: "toc-list" # CSS class for the TOC list to style it with custom CSS.
  sublist_class: "toc-sublist" # CSS class for nested TOC sublists (e.g., for H2 or H3 items).
  item_class: "toc-item" # CSS class for individual items in the TOC list.
  item_prefix: "toc-" # Prefix added to the TOC item ID for easier CSS styling or reference.

# Markdown engine configuration, using Kramdown with GitHub-Flavored Markdown (GFM) support.
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-Flavored Markdown, allowing extra syntax like tables and task lists.
  auto_ids: true # Automatically generate IDs for headings based on their text, used for anchor links.
  toc_levels: 1..3 # Only generate the TOC for headings H1 to H3.

  # Syntax highlighting configuration for code blocks using the Rouge highlighter.
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Configuration options for Rouge syntax highlighter.
    css_class: highlight # The main CSS class applied to code blocks for custom styling.

    span: # Settings for inline code highlighting.
      line_numbers: false # Disables line numbers for inline code blocks.

    block: # Settings for block-level code highlighting (e.g., fenced code blocks).
      line_numbers: true # Enable line numbers for code blocks.
      start_line: 1 # The starting line number for code blocks with line numbers enabled.
      line_class: lineno # CSS class applied to line numbers, useful for custom styling.
      table_class: rouge-table # CSS class applied to the <table> wrapper around the code and line numbers.
      gutter_class: rouge-line # CSS class for the line number column (gutter).
      code_class: rouge-code # CSS class for the actual code content within the code block.

# Pagination configuration for listing posts.
paginate: 8 # Number of posts displayed per page.
paginate_path: "/blog/:num/" # URL structure for paginated pages (e.g., /blog/2/ for the second page).

# Default values for posts. You can override these settings in individual post front matter.
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"
      author:
        <<: *DEFAULT_AUTHOR
      toc: false # Disable the table of contents by default in posts.
      math: false # Disable MathJax for math rendering by default.
      diagram: false # Disable Mermaid.js for diagram rendering by default.
      comments: false # Disable comments by default. To enable, set this to true and configure a comments provider.
      # featured: false # Disable featured post by default. To enable set to `true`

# Theme settings
theme: dblog # The theme used for the site.

# SASS/SCSS settings for styling
sass:
  style: compressed # Compress the compiled CSS to reduce file size.

# Enforce stricter front matter rules to prevent errors in the site build.
strict_front_matter: true # Ensures that all posts and pages have valid front matter.

# Files and directories to exclude from the site build process.
exclude:
  - "scripts/"
  - "vendor/"
  - "tests/"
  - "tools/"
  - "node_modules/"
  - "vercel.json"
  - "package*.json"
  - "LICENSE"
  - "README.md"
